name: Testing configuration variable
on:
  workflow_dispatch
env:
  greeting: Hello
jobs:
  config_job:
    runs-on: ubuntu-latest
    env:
      name: Arjun
    steps: 
      - name: "api key"
        run: echo "$greeting $name your GOOGLE GEMINI API_KEY is ${{vars.GEMINI_API_KEY}}"
