name: User Input
on:
  workflow_dispatch:
    inputs:
      number1:
        description: "first number"
        default: "0"
        required: true
      number2:
        description: "second number"
        default: "0"
        required: true
jobs:
  add_number:
    runs-on: ubuntu-latest

    steps:
      - name: "adding two numbers"
        run: |
          sum=$(( ${{ inputs.number1 }} + ${{ inputs.number2 }} ))
          echo "the sum of ${{inputs.number1}} and ${{inputs.number2}} is $sum "
